apps/cms/urls.py
from django.urls import path
from . import views
app_name = 'cms'

urlpatterns = [
    path('',views.index,name='index')
]

apps/cmsauth/urls.py
from django.urls import path
from . import views
app_name = 'cmsauth'

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('register/',views.register_view,name='register'),
]

apps/news/urls.py
from django.urls import path
from . import views
app_name = 'news'

urlpatterns = [

]

seven_cms/urls.py
from django.urls import path,include
from apps.news import views
urlpatterns = [
    path('',views.index,name='index'),
    path('cms/',include('apps.cms.urls')),
    path('account/',include('apps.cmsauth.urls')),
]

apps/cms/models.py
from django.db import models

# Create your models here.

apps/cmsauth/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,PermissionsMixin,BaseUserManager
# Create your models here.
from shortuuidfield import ShortUUIDField
class UserManager(BaseUserManager):
    def _create_user(self, telephone,username,password,email=None,**kwargs):
        if not telephone:
            raise ValueError('请传入手机号码')
        if not username:
            raise ValueError('请传入用户名')
        if not password:
            raise ValueError('请传入密码')
        user = self.model(telephone=telephone,username=username,email=email,**kwargs)
        user.set_password(password)
        user.save()
        return user

    def create_user(self, telephone,username,password,email=None,**kwargs):
        kwargs['is_staff'] = False
        kwargs['is_superuser'] = False
        return self._create_user(telephone,username, password,email=email,**kwargs)

    def create_superuser(self, telephone,username,password,email=None,**kwargs):
        kwargs['is_staff'] = True
        kwargs['is_superuser'] = True
        return self._create_user(telephone, username,password,email=email,**kwargs)



class User(AbstractBaseUser,PermissionsMixin):
    #主键不使用自增的 101 102 103 104
    # shortuuid pip install django-shortuuidfield
    uid = ShortUUIDField(primary_key=True)
    telephone = models.CharField(max_length=11,unique=True)
    email = models.EmailField(null=True,unique=True)
    username = models.CharField(max_length=100,unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'telephone'
    REQUIRED_FIELDS = ['username']

    objects = UserManager()

    def get_full_name(self):
        return self.username

    def get_black_user(self):
        return self.objects.filter(is_active=False)

apps/news/models.py
from django.db import models

# Create your models here.

apps/cmsauth/forms.py
from django import forms
from django.core import validators
from apps.forms import FromMixin
from .models import User
class LoginForm(forms.Form,FromMixin):
    telephone = forms.CharField(max_length=11,validators=[validators.RegexValidator(r'1[3-8]\d{9}',message='请输入正确的手机号')])
    password = forms.CharField(max_length=30,min_length=6,error_messages={"max_length":"密码最多不能超过30个字符","min_length":"最短不能少于6个字符"})
    remember = forms.IntegerField(required=False)

class RegisterForm(forms.Form,FromMixin):
    telephone = forms.CharField(max_length=11,validators=[validators.RegexValidator(r'1[3-8]\d{9}',message='请输入正确的手机号')])
    username = forms.CharField(max_length=20)
    password1 = forms.CharField(max_length=30,min_length=6,error_messages={"max_length":"密码最多不能超过30个字符","min_length":"最短不能少于6个字符"})
    password2 = forms.CharField(max_length=30,min_length=6,error_messages={"max_length":"密码最多不能超过30个字符","min_length":"最短不能少于6个字符"})

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()

        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')

        if password1 != password2:
            raise forms.ValidationError('两次密码输入不一致')

        telephone = cleaned_data.get('telephone')
        existes = User.objects.filter(telephone=telephone).exists()
        if existes:
            raise forms.ValidationError('该手机号已经存在')

        return cleaned_data

apps/forms.py
class FromMixin(object):
    def get_errors(self):
        if hasattr(self,'errors'):
            errors = self.errors.get_json_data()
            new_errors = {}
            #{'password': [{'message': '最短不能少于6个字符', 'code': 'min_length'}]}
            #{'password':['adf','haha']}
            for key,message_dicts in errors.items():
                messages = []
                for message in message_dicts:
                    messages.append(message['message'])
                new_errors[key] = messages
            return new_errors
        else:
            return {}

apps/cms/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'cms/login.html')

apps/cmsauth/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .forms import LoginForm,RegisterForm
from utils import restful
from django.contrib.auth import login
from .models import User
@require_POST
def login_view(request):
    form = LoginForm(request.POST)
    if form.is_valid():
        telephone = form.cleaned_data.get('telephone')
        password = form.cleaned_data.get('password')
        remember = form.cleaned_data.get('remember')
        user = authenticate(request,username=telephone,password=password)
        if user:
            if user.is_active:
                login(request,user)
                if remember:
                    request.session.set_expiry(None) #两周的时间
                else:
                    request.session.set_expiry(0)
                return restful.success()
            else:
                return restful.unauth(message='您的账号被冻结了')
        else:
            return restful.params_error(message="手机号或者密码错误")

    else:
        errors = form.get_errors()
        return restful.params_error(message=errors)

#注册视图
@require_POST
def register_view(request):
    form = RegisterForm(request.POST)
    if form.is_valid():
        telephone = form.cleaned_data.get('telephone')
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        print(telephone,username,password)
        user = User.objects.create_user(telephone=telephone,username=username,password=password)
        login(request,user) #注册成功以后直接登录
        return restful.success()
    else:
        return restful.params_error(message=form.get_errors())

apps/news/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'news/index.html')

front/templates/base/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{% csrf_token %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="//at.alicdn.com/t/font_681895_q7ptjm0r8n.css">
    <link rel="stylesheet" href="{% static 'css/common/auth.min.css' %}">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    <script src="{% static 'js/qfajax.min.js' %}"></script>
    <script src="{% static 'js/front_base.min.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="logo-box">
                <a href="/"></a>
            </div>

            <ul class="nav">
                <li class="active"><a href="/">创业资讯</a></li>
                <li><a href="">创业课堂</a></li>
                <li><a href="#">付费资讯</a></li>
{#                <li><a href="{% url 'search' %}">搜索</a></li>#}
                <li><a href="/search/">搜索</a></li>
            </ul>

            <div class="auth-box">
                <i class="icon-person iconfont"></i>
                    {% if user.is_authenticated  %}

                    <a href="#" class="authenticated-box">{{ user.username }}</a>
                    <div class="user-more-box">
                        <i class="triangle"></i>
                            {% if user.is_staff %}
                                 <a href="{% url 'cms:index' %}">管理系统</a>
                            {% endif %}
                                <a href="{% url 'qfauth:logout' %}">退出登录</a>

                    </div>
                    {% else %}
                    <a href="#" class="signin-btn">登录</a> /
                    <a href="#" class="signup-btn">注册</a>
                    {% endif %}
            </div>
        </div>
    </header>
    {% block main %}{% endblock %}
    <footer class="footer">
        <div class="top-group">
            <div class="top-inner-group">
                <div class="logo-box"></div>
                <div class="detail-group">
                    <div class="line1">
                        <ul class="links">
                            <li><a href="#">关于小饭桌</a></li>
                            <li><a href="#">创业课堂</a></li>
                            <li><a href="#">寻求报道</a></li>
                            <li><a href="#">创业礼包</a></li>
                        </ul>
                        <div class="about-us">
                            <span class="title">关于我们：</span>
                            <ul class="social-group">
                                <li class="weixin">
                                    <div class="wx-qrcode"></div>
                                    <span class="text">xfz008
                                    </span>
                                </li>
                                <li class="weibo">
                                    <a class="text" href="#">小饭桌创业课堂</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="line2">
                        <p class="address">地址：北京市朝阳区东三环北路38号院1号楼17层2001内1、16室</p>
                        <p class="contact">联系方式：400-810-1090（工作日10点-18点）</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="bottom-group">
            ©2017 北京子木投资顾问有限公司 京ICP备15051289号-1
        </div>
    </footer>
<div class="mask-wrapper">
        <div class="auth-wrapper">
            <div class="close-wrapper">
                <span class="close-btn icon-close iconfont"></span>
            </div>
            <div class="auth-inner-wrapper">
                <div class="scroll-wrapper">
                    <div class="signin-group auth-group">
                        <div class="top-group">
                            <span class="title">请登录</span>
                            <a href="javascript: void(0);" class="switch">立即注册></a>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" name="telephone" placeholder="请输入手机号码">
                            </div>
                             <div class="input-group">
                                <input type="password" class="form-control" name="password" placeholder="请输入密码">
                            </div>
                            <div class="input-group">
                                <label class="remember-label">
                                    <input type="checkbox" name="remember" value="1">
                                    记住我
                                </label>
                            </div>
                            <div class="input-group">
                                <input type="submit" class="submit-btn" value="立即登录">
                            </div>
                        </div>
                    </div>
                    <div class="signup-group auth-group">
                        <div class="top-group">
                            <span class="title">请注册</span>
                            <a href="javascript: void(0);" class="switch">立即登录></a>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" name="telephone" placeholder="手机号码">
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="username" placeholder="用户名">
                            </div>
                            <div class="input-group">
                                <div class="short-input-group">
                                    <input type="text" class="form-control" name="img_captcha" placeholder="图形验证码">
                                </div>
                                <div class="input-group-addon">
                                    <img src="" alt="" class="img-captcha" style="cursor:pointer;">
                                </div>
                            </div>
                            <div class="input-group">
                                <input type="password" class="form-control" name="password1" placeholder="密码">
                            </div>
                            <div class="input-group">
                                <input type="password" class="form-control" name="password2" placeholder="确认密码">
                            </div>
                            <div class="input-group">
                                <div class="short-input-group">
                                    <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
                                </div>
                                <div class="input-group-addon">
                                    <span class="sms-captcha-btn">发送验证码</span>
                                </div>
                            </div>
                            <div class="input-group">
                                <input type="submit" class="submit-btn" value="立即注册">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

front/templates/cms/add_staff.html
{% extends 'cms/base.html' %}

{% block title %}
    添加员工
{% endblock %}

{% block head %}

{% endblock %}

{% block content-header %}
<h1>添加员工</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <div class="box">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="box-body">
                        <div class="form-group">
                            <label for="telephone-input">手机号码：</label>
                            <input type="text" class="form-control" name="telephone">
                        </div>
                        <div class="checkbox">
                            {% for group in groups %}
                                <label style="margin-right:20px;">
                                    <input type="checkbox" name="groups" value="{{ group.pk }}">{{ group.name }}
                                </label>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="box-footer">
                        <button class="btn btn-primary pull-right">立即添加</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/cms/banners.html
{% extends 'cms/base.html' %}

{% block title %}
    轮播图管理
{% endblock %}

{% block head %}
    <style>
    .btn-group{
        float: left;
    }
    .tips{
        float: left;
    }
    .banner-item{
        width: 800px;
    }
    .thumbnail-group{
        float: left;
        width: 230px;
    }
    .thumbnail-group .thumbnail{
        width: 100%;
        height: 84px;
    }
    .more-group{
        float: left;
        margin-left: 20px;
        width: 500px;
    }
    </style>
    <script src="{% static 'arttemplate/template-web.js' %}"></script>
    <script src="{% static 'js/banners.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <h1>轮播图管理</h1>
{% endblock %}

{% block content %}
<div class="row">
<div class="col-md-12">
    <div class="btn-group">
        <button class="btn btn-primary" id="add-banner-btn">
            <i class="fa fa-plus"></i>
            添加轮播图
        </button>
    </div>
    <ul class="tips">
        <li>支持JPG,GIF,PNG格式，最多可上传6张</li>
        <li>比例4：1，宽度在800px以上，5M以内</li>
    </ul>
</div>
</div>
<div class="banner-list-group"></div>

<script id="banner-item" type="text/html">
{% verbatim %}
{{ if banner }}
<div class="box banner-item" data-banner-id="{{ banner.id }}">
{{ else }}
<div class="box banner-item">
{{ /if }}
    <div class="box-header">
        {{ if banner }}
            <span class="priority">优先级：{{ banner.priority }}</span>
        {{ else }}
            <span class="priority">优先级：0</span>
        {{ /if }}
        <button class="btn btn-default btn-xs pull-right close-btn">
            <i class="fa fa-close"></i>
        </button>
    </div>
    <div class="box-body">
        <div class="thumbnail-group">
            <input type="file" style="display: none;" class="image-input">
            {{ if banner }}
                <img src="{{ banner.image_url }}" alt="" class="thumbnail">
            {{ else }}
                <img src="/static/images/banner.png" alt="" class="thumbnail">
            {{ /if }}
        </div>
        <div class="more-group">
            <div class="form-group">
                {{ if banner }}
                    <input type="number" class="form-control" name="priority" value="{{ banner.priority }}">
                {{ else }}
                    <input type="number" class="form-control" name="priority">
                {{ /if }}
            </div>
            <div class="form-group">
                {{ if banner }}
                    <input type="text" class="form-control" name="link_to" value="{{ banner.link_to }}">
                {{ else }}
                    <input type="text" class="form-control" name="link_to">
            </div>
            {{ /if }}
        </div>
    </div>
    <div class="box-footer">
        <button class="btn btn-primary pull-right save-btn">保存</button>
    </div>
</div>
{% endverbatim %}
</script>
{% endblock %}

front/templates/cms/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %} | 千锋学生管理系统</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">
    <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">
    <script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
    <script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/qfajax.min.js' %}"></script>
    <script src="{% static 'js/xfzalert.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <header class="main-header">
        <!-- Logo -->
        <a href="/" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>CMS</b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg">python1904后台管理系统</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="https://tva4.sinaimg.cn/crop.0.2.636.636.180/88c30c5egw1e7ik7e3k6nj20hs0hswgv.jpg"
                                 class="user-image" alt="User Image">
                            <span class="hidden-xs">高海杰</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="https://tva4.sinaimg.cn/crop.0.2.636.636.180/88c30c5egw1e7ik7e3k6nj20hs0hswgv.jpg"
                                     class="img-circle" alt="User Image">
                                <p>
                                    kangbazi
                                    <small>Python web开发工程师</small>
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#" class="btn btn-default btn-flat">个人中心</a>
                                </div>
                                <div class="pull-right">
                                    <a href="{% url 'qfauth:logout' %}" class="btn btn-default btn-flat">退出登录</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="首页">
                    <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
          </span>
                </div>
            </form>
            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="active">
                    <a href="{% url 'cms:index' %}">
                        <i class="fa fa-home"></i>
                        <span>首页</span>
                    </a>
                </li>
                    {% if perms.news.change_news %}
                    <li class="header">新闻管理</li>
                    <li>
                        <a href="{% url 'cms:news_list' %}">
                            <i class="fa fa-list"></i>
                            <span>新闻列表</span>
                        </a>
                    </li>
                    {% endif %}
                    {% if perms.news.add_news %}
                    <li>
                        <a href="{% url 'cms:write_news' %}">
                            <i class="fa fa-edit"></i>
                            <span>发布新闻</span>
                        </a>
                    </li>
                    {% endif %}
                    {% if perms.news.add_newscategory %}
                    <li>
                        <a href="{% url 'cms:news_category' %}">
                            <i class="fa fa-tag"></i>
                            <span>新闻分类</span>
                        </a>
                    </li>
                    {% endif %}
                    {% if perms.news.add_banner %}
                    <li>
                        <a href="#">
                            <i class="fa fa-window-restore"></i>
                            <span>轮播图</span>
                        </a>
                    </li>
                    {% endif %}
                    {% if perms.course.change_course %}
                    <li class="header">课程管理</li>
                    <li>
                        <a href="#">
                            <i class="fa fa-tv"></i>
                            <span>发布课程</span>
                        </a>
                    </li>
                    {% endif %}

                    {% if user.is_superuser %}
                    <li class="header">员工管理</li>
                    <li>
                        <a href="{% url 'cms:staffs' %}">
                            <i class="fa fa-group"></i>
                            <span>员工管理</span>
                        </a>
                    </li>
                    {% endif %}
            </ul>
        </section>
    </aside>
    <div class="content-wrapper">
        <section class="content-header">
            {% block content-header %}{% endblock %}
        </section>
        <section class="content">
            {% block content %}{% endblock %}
        </section>
    </div>
    <footer class="main-footer">
        <strong>python1904</strong>后台管理系统
    </footer>
</div>
</body>
</html>

front/templates/cms/index.html
{% extends 'cms/base.html' %}

{% block title %}首页{% endblock %}

{% block content-header %}
    <h1>欢迎来到千锋武汉Python学生管理系统</h1>
{% endblock %}
</html>

front/templates/cms/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>千锋学生后台管理系统|登录</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/Ionicons/css/ionicons.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/iCheck/square/blue.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="#">学生管理系统</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">请登录</p>

        <form action="{% url 'qfauth:login' %}" method="post">
            {% csrf_token %}
            <div class="form-group has-feedback">
                <input type="text" class="form-control" name="telephone" placeholder="请输入手机号码">
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="password" class="form-control" name="password" placeholder="请输入密码">
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-xs-8">
                    <div class="checkbox icheck">
                        <label>
                            <input type="checkbox" name="remember" value="1"> 记住我
                        </label>
                    </div>
                </div>
                <!-- /.col -->
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">登录</button>
                </div>
                <!-- /.col -->
            </div>
        </form>
    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'adminlte/plugins/iCheck/icheck.min.js' %}"></script>
<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' /* optional */
        });
    });
</script>
</body>
</html>

front/templates/cms/news_category.html
{% extends 'cms/base.html' %}

{% block title %}
    新闻分类
{% endblock %}

{% block head %}
    <script src="{% static 'js/news_category.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <h1>新闻分类</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <button id="add-btn" class="btn btn-primary pull-right">添加分类</button>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>分类名称</th>
                                <th>新闻数量</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for category in categories %}
                                <tr data-pk="{{ category.pk }}" data-name="{{ category.name }}">
                                    <td>{{ category.name }}</td>
                                    <td>20</td>
                                    <td>
                                        <button class="btn btn-warning btn-xs edit-btn">编辑</button>
                                        <button class="btn btn-danger btn-xs delete-btn">删除</button>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}